server:
  port: 1010
spring:
  application:
    name: hrm-config-server
  rabbitmq: #集成RabbitMQ如果配置是默认，可以省略
    host: localhost #mq连接地址
    port: 5672 #mq端口
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lngex/hrm-config.git
          username: lngex
          password: 1902156923aa
          #search-paths: src/main/resources  如果不是在根路径下面需要加搜索地址
#actuator配置
management:
  endpoint:
    health:
      show-details: always #打印日志
  endpoints:
    web:
      exposure:
        include: "*" #向外暴露的接口，这里*则表示所有的actuator接口都可以被访问
    enabled-by-default: true  #开启actuator监控
